export const person = [
  {
    id: 1,
    name: "Leanne Graham",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=George",
    email: "Sincere@april.biz",
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
  },
  {
    id: 2,
    name: "Ervin Howell",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Baby",
    email: "Shanna@melissa.tv",
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Coco",
    email: "Nathan@yesenia.net",
    phone: "493-170-9623 x156",
    website: "kale.biz",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Boo",
    email: "Julianne.OConner@kory.org",
    phone: "493-170-9623 x156",
    website: "kale.biz",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Rascal",
    email: "Lucio_Hettinger@annie.ca",
    phone: "(254)954-1289",
    website: "demarco.info",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Peanut",
    email: "Karley_Dach@jasper.info",
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Sammy",
    email: "Telly.Hoeger@billy.biz",
    phone: "210.067.6132",
    website: "elvis.io",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Callie",
    email: "Sherwood@rosamond.me",
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Midnight",
    email: "Chaim_McDermott@dana.io",
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    avatar: "https://api.dicebear.com/6.x/lorelei/svg?seed=Rocky",
    email: "Rey.Padberg@karina.biz",
    phone: "024-648-3804",
    website: "ambrose.net",
  },
];
